name: Build and Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      
      - name: Build Server
        run: go build cmd/server .
        
      - name: Build Client
        run: go build cmd/client .
        
      - name: Test
        run: go test -v ./...
